pipelines:
  default:
    - parallel:
        - step:
            name: Build & Test 2.7.6
            image: gbrowdy/python-2.7.6
            script: &build_test
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 2.7
            image: python:2.7
            script: *build_test
        - step:
            name: Build & Test 3.4
            image: python:3.4
            script: *build_test
        - step:
            name: Build & Test 3.5
            image: python:3.5
            script: *build_test
        - step:
            name: Build & Test 3.6
            image: python:3.6
            script: *build_test
        - step:
            name: Build & Test 3.7-rc
            image: python:3.7-rc
            script: *build_test
  tags:
    v*:
      - step:
          name: Build Package
          image: python:3.6
          script:
            - pip install wheel
            - python setup.py bdist_wheel --universal
            - ls dist/
          artifacts:
            - dist/*
      - parallel:
        - step:
            name: Test 2.7.6
            image: gbrowdy/python-2.7.6
            script: &deploy_test
              - rm -rf assemblyline_client setup.py
              - pip install -f dist assemblyline_client[test]
              - pytest
        - step:
            name: Test 2.7
            image: python:2.7
            script: *deploy_test
        - step:
            name: Test 3.4
            image: python:3.4
            script: *deploy_test
        - step:
            name: Test 3.5
            image: python:3.5
            script: *deploy_test
        - step:
            name: Test 3.6
            image: python:3.6
            script: *deploy_test
        - step:
            name: Test 3.7-rc
            image: python:3.7-rc
            script: *deploy_test
      - step:
          name: Deploy to Test PyPI
          image: python:3.6
          deployment: test
          script:
            - pip install twine
            - python setup.py sdist
            - ls dist
            - twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
      - step:
          name: Deploy to PyPI
          image: python:3.6
          trigger: manual
          deployment: production
          script:
            - pip install twine
            - python setup.py sdist
            - ls dist
            - twine upload dist/*
